version: '3.4'
services:
  postgres:
    image: postgres
    container_name: postgresql-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shelf
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: