version: '3.4'
services:
  postgres:
    image: postgres
    container_name: postgresql-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shelf
    volumes:
      - /home/clodoaldo/Workspace/data/pgdata:/var/lib/postgresql/data

  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
